- hosts: all
  become: yes
  tasks:
    - name: remove java 
      package:
        name: "{{ package_name }}"
        state: absent
    - name: Install Java
      package:
        name: "{{ package_name }}"
        state: present  
    - name: find the java path
      shell: "{{ java_file_path }}"
      register: java_path
    - debug:
        msg: "Java path is : {{java_path.stdout}}" 
    - name: Line in file
      lineinfile:
        dest: /etc/profile
        line: '{{ item.line }}'
      with_items:
        - {line: 'JAVA_HOME={{java_path.stdout}}'}
        - {line: 'PATH=$PATH:$JAVA_HOME:$HOME/bin'}
    - name: Logoff and login again
      meta: reset_connections    