- hosts: tom
  become: yes
  vars:
    - tomcat_version: 9.0.35
    - tomcat_url: https://downloads.apache.org/tomcat/tomcat-{{tomcat_version.split('.')[0]}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
    - tomcat_port: 8090
  tasks:

    - name: Changing the hostmanager file
      template:
        src: hostmanager.xml.j2
        dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
    - name: Changing the manager context file
      template:
        src: managercontext.xml.j2
        dest: /opt/tomcat/webapps/manager/META-INF/context.xml
    - name: Stopping the tomcat
      shell: nohup /opt/tomcat/bin/shutdown.sh &
    - name: Starting the tomcat
      shell: nohup /opt/tomcat/bin/startup.sh &
    - name: Changing the port
      template:
        src: server.xml.j2
        dest: /opt/tomcat/conf/server.xml
    - name: Changing the users in tomcat-users.xml
      template:
        src: tomcat-users.xml.j2
        dest: /opt/tomcat/conf/tomcat-users.xml                      
