- hosts: all
  become: yes
  vars:
    terra_ver: 0.12.25
    terra_url: https://releases.hashicorp.com/terraform/{{terra_ver}}/terraform_{{ terra_ver}}_linux_amd64.zip  
  tasks:
    - name: Check whether terraform installed or not
      stat:
        path: /opt/terraform
      register: terra_installed
    - name: Install unzip
      package:
        name: unzip
        state: present  
    - name: Download terraform 
      unarchive:
        src: "{{ terra_url }}"
        dest: /opt
        remote_src: yes
    - name: Checking the path
      command: mv /opt/terraform /usr/local/bin
      when: terra_installed.stat.exists        