- hosts: all
  become: yes
  vars:
    - image_version: "{{ version }}" 

  tasks:
    - name: Create a docker image using war file
      docker_image:
        build:
          path: /opt/docker
        name: simple-devops
        tag: "{{ image_version }}"
        source: build
    - name: push the image to docker hub
      docker_image:
        name: simple-devops:{{ image_version }}
        repository: formycore/simple-devops:{{ image_version }}
        push: yes
        source: local
    - name: Remove docker image
      docker_image:
        state: absent
        name: simple-devops
        tag: "{{ image_version }}"
    - name: Remove the tagged image
      docker_image:
        state: absent
        name: formycore/simple-devops
        tag: "{{ image_version }}"